In [1]:
import numpy as np

In [2]:
y_true = np.array([1, 1, 0, 0, 1])
y_predicted = np.array([0.3, 0.7, 1, 0, 0.5])

# Mean Absolute Error

In [3]:
def mean_absolute_error(y_true, y_predicted): # mean absolute error is also called cost function
    total_error = 0
    n = len(y_true)
    for true_value, predicted_value in zip(y_true, y_predicted):
        error = abs(true_value - predicted_value) # error is called loss
        print(error)
        total_error += error
    mae = (1 / n) * total_error
    return f"Total error = {total_error} and Mean Absolute Error is {mae}"

In [4]:
mean_absolute_error(y_true, y_predicted)

0.7
0.30000000000000004
1.0
0.0
0.5


'Total error = 2.5 and Mean Absolute Error is 0.5'

#### instead of writing the whole function above you can take out the mae of the predictions and actual value by this formula

In [5]:
# np.abs returns an array by subtracting each value of y_true with corresponding of y_pred

np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [6]:
# np.mean returns the sum of the array and multiplying it by 1 / n

np.mean(np.abs(y_predicted - y_true)) #abs fucntion converts any negative integer into positive

0.5

# Log Loss OR Binary Crossentorpy

In [7]:
epsilon = 1e-15

y_predicted_new = [max(prediction, epsilon) for prediction in y_predicted]
print(y_predicted)
y_predicted_new

[0.3 0.7 1.  0.  0.5]


[0.3, 0.7, 1.0, 1e-15, 0.5]

In [8]:
print(y_predicted_new)
y_predicted_new = [min(prediction, 1- epsilon) for prediction in y_predicted_new]
y_predicted_new

[0.3, 0.7, 1.0, 1e-15, 0.5]


[0.3, 0.7, 0.999999999999999, 1e-15, 0.5]

In [9]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-1.20397280e+00, -3.56674944e-01, -9.99200722e-16, -3.45387764e+01,
       -6.93147181e-01])

In [10]:
# log loss/binary crossentropy = -(1 / n) * summation ((y * log(y hat)) + (1 - y) * log(1 - y hat))

- np.mean((y_true * np.log(y_predicted_new)) + (1 - y_true) + (np.log(1 - y_predicted_new)))

7.40943316999802

In [11]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(prediction, epsilon) for prediction in y_predicted] # returns a list with 1 for 1 and epsilon for 0
    y_predicted_new = [min(prediction, 1 - epsilon) for prediction in y_predicted_new] # returns a list with 0.9... for 1 and epsilon for epsilon
    y_predicted_new = np.array(y_predicted_new) # returns an array
    return (- np.mean((y_true * np.log(y_predicted_new)) + (1 - y_true) + (np.log(1 - y_predicted_new))))

In [12]:
log_loss(y_true, y_predicted)

7.40943316999802

In [13]:
from sklearn.metrics import log_loss

In [14]:
loss = log_loss(y_true, y_predicted)

In [15]:
loss

7.659489663588355

# Mean Squared Error

In [16]:
mse = np.mean((y_true - y_predicted) ** 2)

In [17]:
mse

0.366

In [18]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_true, y_predicted)

print(f'Mean Squared Error (MSE): {mse}')


Mean Squared Error (MSE): 0.366
